// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands.Zeroing;

import edu.wpi.first.wpilibj2.command.Command;
import frc.robot.subsystems.ElevatorS1;

/**
 *
 */
public class ZeroUpElevatorS2 extends Command {

    private final ElevatorS1 m_elevator;

    public ZeroUpElevatorS2(ElevatorS1 subsystem) {

        m_elevator = subsystem;
        addRequirements(m_elevator);

    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        m_elevator.setElevatorZeroingUpS2();
    }

    @Override
    public void end(boolean interrupted) {
        m_elevator.stopMotorS2();
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return m_elevator.getTopSwitch() || m_elevator.getStalledS2();
    }

}